version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99
    groups:
      dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - 'next'
          - '@next/bundle-analyzer'
          - 'eslint-config-next'
      next:
        patterns:
          - 'next'
          - '@next/bundle-analyzer'
          - 'eslint-config-next'
